import Head from 'next/head';
import { Footer, Navbar } from '../organisms/layout';

type PageWrapperProps = {
  title: string;
  children?: React.ReactNode;
};

const PageWrapper = ({ title, children }: PageWrapperProps) => {
  return (
    <>
      <Head>
        <title>{`${title} | Clean and Tide`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col bg-slate-300">
        {children}
      </main>
      <Footer />
    </>
  );
};

export default PageWrapper;
