import Head from 'next/head';
import { Navbar } from '../organisms';

type PageWrapperProps = {
  title: string;
  children?: React.ReactNode;
};

const PageWrapper = ({ title, children }: PageWrapperProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-slate-300">
        <Navbar />
        {children}
      </main>
    </>
  );
};

export default PageWrapper;
